# Configuration File
# VIXM Algoritmic Trading Signal

data_folder: data

# Key parameters of the model
key_column: VIXM
seed: 19
start_date: 2011-01-05
end_date: 2025-01-05

# Min return to set up a positive signal
threshold: 0.001004

# Min correlation with the key_column (ie. VIXM) to keep the series
min_corr: 0.05

# Split of data
training_period_months: 136 

# Adaboost parameters
adaboost_estimators: 10 
max_depth: 10
learning_rate_adaboost: 1

# Inclusion of the first ppal components lagged
num_pca_components: 40  # n
num_lags_to_include: 5  # t

# Definition of demo mode or development mode
demo_mode: False
tuning_mode: True
run_multiple_tuning_iterations: False

# Ticker List: key_column (defined above) (ie.VIXM) must be placed in first position
ticker_list:
  - VIXM
  - ^VIX
  - SPY
  - VIXY
  - GBPUSD=X
  - BRLUSD=X
  - DX-Y.NYB
  - USDJPY=X
  - ^TNX
  - ZF=F
  - NQ=F
  - NKD=F
  - LQD
  - AAPL
  - AMZN
  - MU
  - MSFT
  - BMY
  - PLD
  - FXI
  - FEZ
  - ^FTSE
  - ^FCHI
  - ^GSPC
  - GLD
  - SLV
  - ES=F
  - QM=F
  - BIO=F
  - AGG
  
garch_not_to_include: 
    - BIO=F

windows_for_volatility_lags: # in days
    - 10
    - 20
    - 30
    - 60
    - 90
    - 120
    - 180
    - 200
    - 260
component_names:
    1: prices
    2: return
    3: volume
    4: garch
    5: return_squared
    6: spy_volatilities_lags
    10: day-of_week_effect
    11: month_effect
    

#Some of the less familiar tickers are listed below, together with others that can be good to try again in the future
#Bristol-Myers Squibb Company (BMY)
#E-Mini Nasdaq                (BIO=F)
#Euro spot                    (EURUSD)
#E-Mini S&P500                (ES=F)
#CAC 40                       (^FCHI)
#FTSE 100                     (^FTSE)
#SPDR EURO STOXX 50 ETF       (FEZ)
#FEDEX CORP                   (FDX)
#The Goldman Sachs Group, Inc.(GS)
#DAX PERFORMANCE-INDEX        (^GDAXI)
#S&P500 Index                 (^GSPC)
#HANG SENG INDEX              (^HSI)
#13 Week Treasury Bill        (^IRX) 
#iShares iBoxx $ Investment Grade Corporate Bond ETF (LQD)
#Micron Technology, Inc.      (MU)
#Microsoft Corporation        (MSFT)
#Nikkei/USD Futures,Dec-2021 (NKD=F)
#Nasdaq 100 Dec 21           (NQ=F)
#NVIDIA Corporation          (NVDA)
#E-Mini oil                  (QM=F)
#Prologis, Inc.              (PLD)
#Treasury Yield 10 Years     (^TNX) -- 1985
#Yen Denominated TOPIX Futures,D   (TPY=F)
#American Funds U.S. Government Securities Fund Class C (UGSCX) - 2001
#Energy Select Sector SPDR Fund    (XLE)
#Financial Select Sector SPDR Fund (XLF)
#U.S. Treasury Bond Futures,Dec-   (ZB=F) - 2000
#Five-Year US Treasury Note Futu   (ZF=F) - 2000
